apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: aws-sdlc-containers-catalog
  description: Root Backstage catalog location for platform monorepo entities.
spec:
  type: file
  targets:
    - ./catalog/platform-engineering-group.yaml
    - ./catalog/platform-engineering-domain.yaml
    - ./catalog/aws-sdlc-containers-system.yaml
    - ./catalog/runtime-target-local-compose.yaml
    - ./catalog/runtime-target-aws-ecs.yaml
    - ./catalog/platform-monorepo-component.yaml
    - ./catalog/api-component.yaml
    - ./catalog/event-consumer-component.yaml
    - ./catalog/foreign-inventory-sync-component.yaml
    - ./catalog/backfill-worker-component.yaml
    - ./catalog/churn-model-train-job-component.yaml
    - ./catalog/churn-prediction-api-component.yaml
    - ./catalog/data-export-job-component.yaml
    - ./catalog/open-dataset-pipeline-component.yaml
    - ./catalog/lake-orders-ingest-job-component.yaml
    - ./catalog/operational-snapshot-job-component.yaml
    - ./catalog/integration-check-job-component.yaml
