[project]
name = "aws-sdlc-containers-order-event-consumer"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aws-sdlc-containers-application",
    "aws-sdlc-containers-infrastructure",
    "fastapi>=0.111.0",
    "pydantic>=2.7.1",
    "pydantic-settings>=2.3.0",
    "uvicorn[standard]>=0.29.0",
]
