apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: churn_prediction_api
  description: Experimental inference workload that serves only compatible, promoted model artifacts.
  tags:
    - internal-api
    - mlops-serving
    - model-inference
spec:
  type: service
  lifecycle: experimental
  owner: group:default/platform-engineering
  system: aws-sdlc-containers
  dependsOn:
    - resource:default/runtime-target-local-compose
