apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: platform-engineering
  description: Internal platform engineering standards, delivery, and workload enablement.
spec:
  owner: group:default/platform-engineering
