[SERVICE]
    Flush 1
    Grace 30
    Log_Level info

[OUTPUT]
    Name cloudwatch_logs
    Match app-firelens*
    region ${AWS_REGION}
    log_group_name /ecs/${STACK_NAME}/app
    log_stream_prefix firelens/
    auto_create_group false

[OUTPUT]
    Name loki
    Match app-firelens*
    Host ${LOKI_HOST}
    Port ${LOKI_PORT}
    Labels stack=${STACK_NAME},environment=${ENVIRONMENT},service=app,container=app

[OUTPUT]
    Name cloudwatch_logs
    Match pgbouncer-firelens*
    region ${AWS_REGION}
    log_group_name /ecs/${STACK_NAME}/pgbouncer
    log_stream_prefix firelens/
    auto_create_group false

[OUTPUT]
    Name loki
    Match pgbouncer-firelens*
    Host ${LOKI_HOST}
    Port ${LOKI_PORT}
    Labels stack=${STACK_NAME},environment=${ENVIRONMENT},service=app,container=pgbouncer

[OUTPUT]
    Name cloudwatch_logs
    Match worker-firelens*
    region ${AWS_REGION}
    log_group_name /ecs/${STACK_NAME}/worker
    log_stream_prefix firelens/
    auto_create_group false

[OUTPUT]
    Name loki
    Match worker-firelens*
    Host ${LOKI_HOST}
    Port ${LOKI_PORT}
    Labels stack=${STACK_NAME},environment=${ENVIRONMENT},service=worker,container=worker

[OUTPUT]
    Name cloudwatch_logs
    Match data-export-job-firelens*
    region ${AWS_REGION}
    log_group_name /ecs/${STACK_NAME}/data-export-job
    log_stream_prefix firelens/
    auto_create_group false

[OUTPUT]
    Name loki
    Match data-export-job-firelens*
    Host ${LOKI_HOST}
    Port ${LOKI_PORT}
    Labels stack=${STACK_NAME},environment=${ENVIRONMENT},service=data-export-job,container=data-export-job

[OUTPUT]
    Name cloudwatch_logs
    Match order-event-consumer-firelens*
    region ${AWS_REGION}
    log_group_name /ecs/${STACK_NAME}/order-event-consumer
    log_stream_prefix firelens/
    auto_create_group false

[OUTPUT]
    Name loki
    Match order-event-consumer-firelens*
    Host ${LOKI_HOST}
    Port ${LOKI_PORT}
    Labels stack=${STACK_NAME},environment=${ENVIRONMENT},service=order-event-consumer,container=order-event-consumer

[OUTPUT]
    Name cloudwatch_logs
    Match liquibase-firelens*
    region ${AWS_REGION}
    log_group_name /ecs/${STACK_NAME}/liquibase
    log_stream_prefix firelens/
    auto_create_group false

[OUTPUT]
    Name loki
    Match liquibase-firelens*
    Host ${LOKI_HOST}
    Port ${LOKI_PORT}
    Labels stack=${STACK_NAME},environment=${ENVIRONMENT},service=liquibase,container=liquibase

[OUTPUT]
    Name cloudwatch_logs
    Match grafana-firelens*
    region ${AWS_REGION}
    log_group_name /ecs/${STACK_NAME}/grafana
    log_stream_prefix firelens/
    auto_create_group false

[OUTPUT]
    Name loki
    Match grafana-firelens*
    Host ${LOKI_HOST}
    Port ${LOKI_PORT}
    Labels stack=${STACK_NAME},environment=${ENVIRONMENT},service=grafana,container=grafana

[OUTPUT]
    Name cloudwatch_logs
    Match prometheus-firelens*
    region ${AWS_REGION}
    log_group_name /ecs/${STACK_NAME}/prometheus
    log_stream_prefix firelens/
    auto_create_group false

[OUTPUT]
    Name loki
    Match prometheus-firelens*
    Host ${LOKI_HOST}
    Port ${LOKI_PORT}
    Labels stack=${STACK_NAME},environment=${ENVIRONMENT},service=prometheus,container=prometheus

[OUTPUT]
    Name cloudwatch_logs
    Match loki-firelens*
    region ${AWS_REGION}
    log_group_name /ecs/${STACK_NAME}/loki
    log_stream_prefix firelens/
    auto_create_group false

[OUTPUT]
    Name loki
    Match loki-firelens*
    Host ${LOKI_HOST}
    Port ${LOKI_PORT}
    Labels stack=${STACK_NAME},environment=${ENVIRONMENT},service=loki,container=loki

[OUTPUT]
    Name cloudwatch_logs
    Match tempo-firelens*
    region ${AWS_REGION}
    log_group_name /ecs/${STACK_NAME}/tempo
    log_stream_prefix firelens/
    auto_create_group false

[OUTPUT]
    Name loki
    Match tempo-firelens*
    Host ${LOKI_HOST}
    Port ${LOKI_PORT}
    Labels stack=${STACK_NAME},environment=${ENVIRONMENT},service=tempo,container=tempo
