apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: async-eventing-resiliency
scopes:
  - event-consumer
  - booking-api
spec:
  policies:
    timeouts:
      asyncEventsPubsub: 10s
      serviceInvocation: 5s
    retries:
      asyncEventsPubsub:
        policy: constant
        duration: 1s
        maxRetries: 2
      serviceInvocation:
        policy: constant
        duration: 250ms
        maxRetries: 2
    circuitBreakers:
      asyncEventsPubsub:
        maxRequests: 1
        interval: 30s
        timeout: 30s
        trip: consecutiveFailures > 5
      serviceInvocation:
        maxRequests: 1
        interval: 30s
        timeout: 15s
        trip: consecutiveFailures > 5
  targets:
    components:
      async-events-pubsub:
        outbound:
          timeout: asyncEventsPubsub
          retry: asyncEventsPubsub
          circuitBreaker: asyncEventsPubsub
        inbound:
          timeout: asyncEventsPubsub
          retry: asyncEventsPubsub
          circuitBreaker: asyncEventsPubsub
    apps:
      booking-api:
        timeout: serviceInvocation
        retry: serviceInvocation
        circuitBreaker: serviceInvocation
