{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "install.yaml",
    "argocd-secrets.yaml",
    "session-secret.yaml"
  ],
  "configMapGenerator": [
    {
      "name": "platform-config",
      "namespace": "backstage",
      "files": [
        "app-config.yaml",
        "k8s-config.yaml"
      ]
    }
  ],
  "patches": [
    {
      "path": "deployment.yaml"
    },
    {
      "target": {
        "group": "rbac.authorization.k8s.io",
        "kind": "ClusterRole|ClusterRoleBinding"
      },
      "patch": "$patch: delete\napiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRole\nmetadata:\n  name: unused"
    },
    {
      "target": {
        "kind": "Secret",
        "name": "k8s-config"
      },
      "patch": "$patch: delete\napiVersion: v1\nkind: Secret\nmetadata:\n  name: k8s-config"
    }
  ]
}
